### ISSUE TITLE
Error during load

### ISSUE THREAD

**Issue by colormeblind23** [bradxy/sell-vehicles-vrp2#1]
Error resuming coroutine: citizen:/scripting/lua/scheduler.lua:24: Failed to execute thread: [string "sell_vehicles_vrp2/server.lua"]:357: attempt to index a nil value (local 'gcfg')
stack traceback:
	[string "sell_vehicles_vrp2/server.lua"]:357: in upvalue 'func'
	[string "vrp/vRPShared.lua"]:113: in function <[string "vrp/vRPShared.lua"]:112>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:24: in field 'CreateThreadNow'
	@vrp/lib/utils.lua:85: in function 'async'
	[string "vrp/vRPShared.lua"]:112: in method 'triggerEvent'
	[string "vrp/vRP.lua"]:533: in function <[string "vrp/vRP.lua"]:532>

This occurs during load of player character, causes loading sequence to stop mid way
Running off VRP 2.0 with a dedicated server box

**Comment by bradxy** [comment]
Added missing config 8469ca3
