### ISSUE TITLE
error when loading script

### ISSUE THREAD

**Issue by cyberthugig** [bradxy/sell-vehicles-vrp2#2]
Error running system event handling function for resource vrp: citizen:/scriptin
g/lua/scheduler.lua:24: Failed to execute thread: @vrp/lib/utils.lua:51: resourc
e file sell_vehicles_vrp2/server.lua not found
stack traceback:
        [C]: in function 'error'
        @vrp/lib/utils.lua:51: in function 'module'
        @vrp/base.lua:14: in local 'f'
        [string "vrp/lib/Proxy.lua"]:59: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:171: in function <citizen:/scriptin
g/lua/scheduler.lua:170>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:24: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:170: in function <citizen:/scriptin
g/lua/scheduler.lua:134>
Started resource sell-vehicles-vrp2

**Comment by bradxy** [comment]
change the folder name to sell_vehicles_vrp2
